services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.2.1
    restart: always
    ports:
      - "9090:9090"
    environment:
      TZ: UTC
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - ./custom-rules:/etc/prometheus/custom-rules
      - /data/monitoring/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=2h'
      - '--storage.tsdb.min-block-duration=2h'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--storage.tsdb.retention.time=30d'

  alertmanager:
    container_name: alertmanager
    image: bitnami/alertmanager:0.26.0
    restart: always
    ports:
      - "9093:9093"
    environment:
      TZ: UTC
    volumes:
      - ./alertmanager.yml:/opt/bitnami/alertmanager/conf/config.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:11.5.2
    restart: always
    ports:
      - "3000:3000"
    environment:
      TZ: UTC
      GF_ANGULAR_SUPPORT_ENABLED: true
    volumes:
      - /data/monitoring/grafana-data:/var/lib/grafana
      # 挂载 grafana.ini 主要目的在于启用 angular_support_enabled = true
      - ./grafana.ini:/etc/grafana/grafana.ini

  blackbox_exporter:
    container_name: blackbox_exporter
    image: quay.io/prometheus/blackbox-exporter:latest
    restart: always
    ports:
      - "9115:9115"
    environment:
      TZ: UTC

  tg_bot:
    container_name: tg_bot
    image: metalmatze/alertmanager-bot:0.4.3
    restart: always
    ports:
      - "8080:8080"
    environment:
      TZ: UTC
      ALERTMANAGER_URL: http://alertmanager:9093
      TELEGRAM_ADMIN: 1234567890                                        # 管理员用户ID，可通过用户@userinfobot获取到
      TELEGRAM_TOKEN: 1111111111:AAAAAAABBBBBBBBBBCCCCCCCCDDDDDDDDDD    # 用于访问API的TOKEN，可通过用户@BotFather获取到
      STORE: bolt
      BOLT_PATH: /data/bot.db

  dingtalk_bot:
    container_name: dingtalk_bot
    build:
      context: .
      dockerfile: dingtalk.Dockerfile
    image: dingtalkbot:2.1.0
    restart: always
    command: ./prometheus-webhook-dingtalk --config.file=dingtalk.yml --web.listen-address=:8060
    ports:
      - "8060:8060"
    environment:
      TZ: UTC
    volumes:
      - ./dingtalk.yml:/usr/local/prometheus-webhook-dingtalk-2.1.0.linux-amd64/dingtalk.yml