{
 "title": "Fleet / Cluster",
 "description": "Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(fleet_cluster_desired_ready_git_repos, exported_namespace)"
   },
   {
    "name": "name",
    "query": "label_values(fleet_cluster_desired_ready_git_repos{exported_namespace=~\"$namespace\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ready Git Repos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(fleet_cluster_ready_git_repos{exported_namespace=\"$namespace\",name=~\"$name\"}) / sum(fleet_cluster_desired_ready_git_repos{exported_namespace=\"$namespace\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "Git Repos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(fleet_cluster_desired_ready_git_repos{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Desired Ready"
    },
    {
     "expr": "sum(fleet_cluster_ready_git_repos{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Git Repos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(fleet_cluster_desired_ready_git_repos{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Desired Ready"
    },
    {
     "expr": "sum(fleet_cluster_ready_git_repos{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Ready Resources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(fleet_cluster_resources_count_ready{exported_namespace=\"$namespace\",name=~\"$name\"}) / sum(fleet_cluster_resources_count_desiredready{exported_namespace=\"$namespace\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 13 },
   "targets": [
    {
     "expr": "sum(fleet_cluster_resources_count_desiredready{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Desired Ready"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_ready{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_notready{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_missing{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_modified{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Modified"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_unknown{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_orphaned{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Orphaned"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_waitapplied{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Wait Applied"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(fleet_cluster_resources_count_desiredready{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Desired Ready"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_ready{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_notready{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_missing{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_modified{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Modified"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_unknown{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_orphaned{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Orphaned"
    },
    {
     "expr": "sum(fleet_cluster_resources_count_waitapplied{exported_namespace=\"$namespace\",name=~\"$name\"})",
     "legendFormat": "Wait Applied"
    }
   ]
  },
  {
   "title": "Ready Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(fleet_cluster_state{exported_namespace=\"$namespace\",name=~\"$name\",state=\"Ready\"}) / sum(fleet_cluster_state{exported_namespace=\"$namespace\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 26 },
   "targets": [
    {
     "expr": "sum(fleet_cluster_state{exported_namespace=\"$namespace\",name=~\"$name\",state=\"Ready\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(fleet_cluster_state{exported_namespace=\"$namespace\",name=~\"$name\",state=\"NotReady\"})",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "sum(fleet_cluster_state{exported_namespace=\"$namespace\",name=~\"$name\",state=\"WaitCheckIn\"})",
     "legendFormat": "Wait Check In"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(fleet_cluster_state{exported_namespace=\"$namespace\",name=~\"$name\",state=\"Ready\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(fleet_cluster_state{exported_namespace=\"$namespace\",name=~\"$name\",state=\"NotReady\"})",
     "legendFormat": "Not Ready"
    },
    {
     "expr": "sum(fleet_cluster_state{exported_namespace=\"$namespace\",name=~\"$name\",state=\"WaitCheckIn\"})",
     "legendFormat": "Wait Check In"
    }
   ]
  }
 ]
}