{
 "title": "Rancher / Kubernetes Components (Nodes)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API Server Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[$__rate_interval])) by (instance, code)",
     "legendFormat": "{{code}}({{instance}})"
    }
   ]
  },
  {
   "title": "Controller Manager Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"deployment\"}) by (instance, name)",
     "legendFormat": "Deployment Depth ({{instance}})"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"volumes\"}) by (instance, name)",
     "legendFormat": "Volumes Depth ({{instance}})"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"replicaset\"}) by (instance, name)",
     "legendFormat": "ReplicaSet Depth ({{instance}})"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"service\"}) by (instance, name)",
     "legendFormat": "Service Depth ({{instance}})"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"serviceaccount\"}) by (instance, name)",
     "legendFormat": "ServiceAccount Depth ({{instance}})"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"endpoint\"}) by (instance, name)",
     "legendFormat": "Endpoint Depth ({{instance}})"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"daemonset\"}) by (instance, name)",
     "legendFormat": "DaemonSet Depth ({{instance}})"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"statefulset\"}) by (instance, name)",
     "legendFormat": "StatefulSet Depth ({{instance}})"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"replicationmanager\"}) by (instance, name)",
     "legendFormat": "ReplicationManager Depth ({{instance}})"
    }
   ]
  },
  {
   "title": "Pod Scheduling Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{condition=\"false\"})",
     "legendFormat": "Failed To Schedule"
    }
   ]
  },
  {
   "title": "Ingress Controller Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"reading\"}) by (instance)",
     "legendFormat": "Reading ({{instance}})"
    },
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"waiting\"}) by (instance)",
     "legendFormat": "Waiting ({{instance}})"
    },
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"writing\"}) by (instance)",
     "legendFormat": "Writing ({{instance}})"
    },
    {
     "expr": "sum(ceil(increase(nginx_ingress_controller_nginx_process_connections_total{state=\"accepted\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "Accepted ({{instance}})"
    },
    {
     "expr": "sum(ceil(increase(nginx_ingress_controller_nginx_process_connections_total{state=\"handled\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "Handled ({{instance}})"
    }
   ]
  }
 ]
}