{
 "title": "Rancher / Kubernetes Components",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API Server Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Controller Manager Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"deployment\"}) by (name)",
     "legendFormat": "Deployment Depth"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"volumes\"}) by (name)",
     "legendFormat": "Volumes Depth"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"replicaset\"}) by (name)",
     "legendFormat": "Replicaset Depth"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"service\"}) by (name)",
     "legendFormat": "Service Depth"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"serviceaccount\"}) by (name)",
     "legendFormat": "ServiceAccount Depth"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"endpoint\"}) by (name)",
     "legendFormat": "Endpoint Depth"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"daemonset\"}) by (name)",
     "legendFormat": "DaemonSet Depth"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"statefulset\"}) by (name)",
     "legendFormat": "StatefulSet Depth"
    },
    {
     "expr": "sum(workqueue_depth{component=\"kube-controller-manager\", name=\"replicationmanager\"}) by (name)",
     "legendFormat": "ReplicationManager Depth"
    }
   ]
  },
  {
   "title": "Pod Scheduling Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{condition=\"false\"})",
     "legendFormat": "Failed To Schedule"
    }
   ]
  },
  {
   "title": "Ingress Controller Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"reading\"})",
     "legendFormat": "Reading"
    },
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"waiting\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"writing\"})",
     "legendFormat": "Writing"
    },
    {
     "expr": "sum(ceil(increase(nginx_ingress_controller_nginx_process_connections_total{state=\"accepted\"}[$__rate_interval])))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(ceil(increase(nginx_ingress_controller_nginx_process_connections_total{state=\"handled\"}[$__rate_interval])))",
     "legendFormat": "Handled"
    }
   ]
  }
 ]
}