apiVersion: v1
kind: Service
metadata:
  name: nodeport-grafana
  namespace: cattle-monitoring-system
spec:
  ports:
    - name: http
      nodePort: 31337
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
  type: NodePort