apiVersion: v1
kind: Service
metadata:
  name: nodeport-prometheus
  namespace: cattle-monitoring-system
spec:
  ports:
    - name: http
      nodePort: 30909
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
  type: NodePort